version: '2'
services:
  webapp:
    container_name: wb-standard-dev
    build:
      context: ./
      dockerfile: Dockerfile-PHP
    volumes:
      - "../../:/var/www/html/"
    privileged: true
    working_dir: /var/www/html
    command: sleep 10000000


